-- Örnek etkinlikler (ana sayfa slayt + takvim)
-- Supabase SQL Editor'da çalıştırın. Tablo yoksa önce events.sql veya events-migrate.sql.

insert into public.events (
  slug,
  title,
  title_plain,
  description,
  body,
  category,
  date_display,
  date,
  event_time,
  location,
  duration,
  poster_url,
  featured,
  status,
  schedule
)
values
  (
    'pulumur-krom-ocagi-halk-bulusmasi',
    'Pülümür Krom Ocağına Karşı Halk Buluşması',
    'Pülümür Krom Ocağına Karşı Halk Buluşması',
    'Dimin Madencilik''in Hel Dağı''ndaki krom ocağı projesine karşı halk buluşması. Munzur Çevre Derneği Dersim Temsilciliği ve yöre köy derneklerinin çağrısıyla.',
    '["Açılış ve bilgilendirme","Ortak mücadele çağrısı","Basın açıklaması"]'::jsonb,
    'Halk Buluşması',
    '14 Haziran 2026, Cumartesi',
    '2026-06-14',
    '13:00',
    'Pülümür, Dersim',
    'Tam gün',
    '/photos/pazar-eylemi.png',
    true,
    'published',
    '[{"time":"13:00","label":"Toplanma"},{"time":"14:00","label":"Halk buluşması"},{"time":"16:00","label":"Basın açıklaması"}]'::jsonb
  ),
  (
    'ges-projelerine-karsi-dersim-bulusmasi',
    'Dersim''de GES''lere Karşı Örgütlenme Buluşması',
    'Dersim''de GES''lere Karşı Örgütlenme Buluşması',
    'Pertek ve Hozat''taki güneş enerjisi santrali planlarına karşı «Rızamız yok» şiarıyla basın açıklaması ve örgütlenme toplantısı.',
    '["GES projelerine genel bakış","Hukuki süreçler","Ortak eylem planı"]'::jsonb,
    'Basın & Örgütlenme',
    '5 Temmuz 2026, Pazar',
    '2026-07-05',
    '11:00',
    'Tunceli Merkez',
    '3 saat',
    '/photos/varto-eylemi.png',
    true,
    'published',
    '[{"time":"11:00","label":"Basın açıklaması"},{"time":"12:30","label":"Atölye ve soru-cevap"}]'::jsonb
  ),
  (
    'munzur-gozeleri-koruma-yuruyusu',
    'Munzur Gözeleri İçin Tam Koruma Yürüyüşü',
    'Munzur Gözeleri İçin Tam Koruma Yürüyüşü',
    'Munzur Gözeleri''nin koruma statüsünün düşürülmesine ve maden baskısına karşı tam koruma talebiyle yürüyüş.',
    '["Korteje katılım","Yürüyüş","Sonuç bildirisi"]'::jsonb,
    'Yürüyüş',
    '22 Mart 2026, Pazar',
    '2026-03-22',
    '10:00',
    'Ovacık — Munzur Vadisi',
    '5 saat',
    '/photos/saha-bulusma.png',
    false,
    'published',
    '[{"time":"10:00","label":"Toplanma"},{"time":"11:00","label":"Yürüyüş"}]'::jsonb
  ),
  (
    'havacor-dogaya-ve-yasam-nobeti-acilisi',
    'Havaçor Doğa ve Yaşam Nöbeti Açılışı',
    'Havaçor Doğa ve Yaşam Nöbeti Açılışı',
    'Ovacık Havaçor''da bir ay sürecek doğa ve yaşam nöbetinin açılış programı; köy dernekleri ve çevre örgütleriyle dayanışma.',
    '["Nöbet alanı kurulumu","Açılış konuşmaları","Kardeş örgüt mesajları"]'::jsonb,
    'Nöbet & Eylem',
    '8 Şubat 2026, Pazar',
    '2026-02-08',
    '09:00',
    'Havaçor Köyü, Ovacık',
    'Tam gün',
    '/photos/pazar-afis.png',
    false,
    'published',
    '[]'::jsonb
  )
on conflict (slug) do update set
  title = excluded.title,
  title_plain = excluded.title_plain,
  description = excluded.description,
  body = excluded.body,
  category = excluded.category,
  date_display = excluded.date_display,
  date = excluded.date,
  event_time = excluded.event_time,
  location = excluded.location,
  duration = excluded.duration,
  poster_url = excluded.poster_url,
  featured = excluded.featured,
  status = excluded.status,
  schedule = excluded.schedule,
  updated_at = now();
